from flask import Request, Response
from wtforms.form import Form
from typing import Any, Optional, Type

class FlaskForm(Form):
    csrf_token: Any

    def validate_on_submit(self) -> bool: ...
    def is_submitted(self) -> bool: ...

class CSRFProtect:
    def __init__(self, app: Optional[Any] = ...) -> None: ...
    def init_app(self, app: Any) -> None: ...
    def protect(self) -> None: ...
    def exempt(self, view: Any) -> Any: ...
    def generate_csrf(self, secret_key: Optional[str] = ..., token_key: Optional[str] = ...) -> str: ...
    def validate_csrf(self, data: str, secret_key: Optional[str] = ..., token_key: Optional[str] = ...) -> None: ...
    def _get_token(self) -> str: ...