from typing import Any, Callable, Optional, Union
from datetime import datetime
from flask import Flask

class Babel:
    def __init__(self, app: Optional[Flask] = ...) -> None: ...
    def init_app(self, app: Flask) -> None: ...
    def localeselector(self, func: Callable[[], str]) -> Callable[[], str]: ...
    def timezoneselector(self, func: Callable[[], str]) -> Callable[[], str]: ...

def gettext(string: str, **variables: Any) -> str: ...
_=gettext
def ngettext(singular: str, plural: str, num: int, **variables: Any) -> str: ...
def lazy_gettext(string: str) -> Any: ...
def lazy_ngettext(singular: str, plural: str, num: int) -> Any: ...
def pgettext(context: str, string: str, **variables: Any) -> str: ...
def npgettext(context: str, singular: str, plural: str, num: int, **variables: Any) -> str: ...

def format_datetime(datetime: datetime = ..., format: Optional[str] = ...) -> str: ...
def format_date(date: datetime = ..., format: Optional[str] = ...) -> str: ...
def format_time(time: datetime = ..., format: Optional[str] = ...) -> str: ...
def format_timedelta(delta: Union[datetime, int], granularity: str = ..., threshold: float = ...) -> str: ...