from typing import Any

class Format: ...

class Worksheet:
    def write(self, row: int, col: int, data: Any, cell_format: Format | None = ...) -> int: ...
    def write_string(self, row: int, col: int, string: str, cell_format: Format | None = ...) -> int: ...
    def write_number(self, row: int, col: int, number: float, cell_format: Format | None = ...) -> int: ...
    def write_blank(self, row: int, col: int, cell_format: Format | None = ...) -> int: ...
    def set_column(self, first_col: int, last_col: int, width: float, cell_format: Format | None = ..., options: dict[str, Any] | None = ...) -> None: ...
    def write_url(self, row: int, col: int, url: str, cell_format: Format | None = ..., string: str | None = ...) -> int: ...
    def insert_image(self, row: int, col: int, filename: str, options: dict[str, Any] | None = ...) -> None: ...
    def merge_range(self, first_row: int, first_col: int, last_row: int, last_col: int, data: Any, cell_format: Format | None = ...) -> int: ...

class Workbook:
    def __init__(self, filename: str, *args: Any, **kwargs: Any): ...
    def add_worksheet(self, name: str = ...) -> Worksheet: ...
    def add_format(self, properties: dict[str, Any] | None = ...) -> Format: ...
    def close(self) -> None: ...