site_name: Chrono Des Vignes Documentation
site_url: https://chronodesvignes.eu.pythonanywhere.com/doc/


repo_url: https://github.com/pythonhtmlcssjsarduino/chrono_des_vignes_2.0
nav:
  - retour au site: https://chronodesvignes.eu.pythonanywhere.com
  - Home: index.md
  - Users: users.md
  - Organisateurs:
    - organisateurs/index.md
    - Parcours: organisateurs/parcours.md
    - Edition: 
      - organisateurs/edition/index.md
      - Chronometrage: organisateurs/edition/chronometrage.md
      - Dossard: organisateurs/edition/dossard.md
      - Parcours: organisateurs/edition/parcours.md
      - Resultats: organisateurs/edition/resultats.md
    - Coureurs: organisateurs/coureurs.md

not_in_nav: 
  example.md

extra_css:
  - style.css

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
