site_name: Chrono Des Vignes Documentation
site_url: https://sitename.example

repo_url: https://github.com/pythonhtmlcssjsarduino/chrono_des_vignes_2.0
nav:
  - Home: index.fr.md
  - About: about.fr.md
  - Users: users.fr.md
  - Organisateurs: organisateurs.fr.md

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg