"""second migration

Revision ID: 34700a04af2e
Revises: 5b122d22803a
Create Date: 2024-09-18 17:39:59.439261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34700a04af2e'
down_revision = '5b122d22803a'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passagekey_stand',
    sa.Column('passage_key_id', sa.Integer(), nullable=True),
    sa.Column('stand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passage_key_id'], ['passage_key.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stand.id'], )
    )
    with op.batch_alter_table('passage', schema=None) as batch_op:
        batch_op.alter_column('inscrit_id', new_column_name='inscription_id')

    with op.batch_alter_table('passage_key', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_passage_key_stand_id_stand', type_='foreignkey')
        batch_op.drop_column('stand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passage_key', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('stand_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_passage_key_stand_id_stand'), 'stand', ['stand_id'], ['id'])

    with op.batch_alter_table('passage', schema=None) as batch_op:
        batch_op.alter_column('inscription_id', new_column_name='inscrit_id')

    op.drop_table('passagekey_stand')
    # ### end Alembic commands ###
