"""initial migration

Revision ID: 5b122d22803a
Revises: 
Create Date: 2024-09-17 19:37:11.897559

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5b122d22803a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('avatar', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('datenaiss', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('createur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['createur_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('edition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('edition_date', sa.DateTime(), nullable=False),
    sa.Column('first_inscription', sa.DateTime(), nullable=False),
    sa.Column('last_inscription', sa.DateTime(), nullable=False),
    sa.Column('rdv_lat', sa.Float(), nullable=False),
    sa.Column('rdv_lng', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('chronos_list', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editions_parcours',
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.Column('parcours_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], )
    )
    op.create_table('inscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('parcours_id', sa.Integer(), nullable=False),
    sa.Column('dossard', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('parcours_id', sa.Integer(), nullable=True),
    sa.Column('start_stand', sa.Integer(), nullable=True),
    sa.Column('end_stand', sa.Integer(), nullable=True),
    sa.Column('color', sqlalchemy_utils.types.color.ColorType(length=20), nullable=False),
    sa.Column('chrono', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['end_stand'], ['parcours.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], ),
    sa.ForeignKeyConstraint(['start_stand'], ['parcours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passage_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('parcours_id', sa.Integer(), nullable=False),
    sa.Column('stand_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('parcours_id', sa.Integer(), nullable=True),
    sa.Column('start_id', sa.Integer(), nullable=False),
    sa.Column('end_id', sa.Integer(), nullable=False),
    sa.Column('trace', sa.Text(), nullable=False),
    sa.Column('turn_nb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['end_id'], ['stand.id'], ),
    sa.ForeignKeyConstraint(['parcours_id'], ['parcours.id'], ),
    sa.ForeignKeyConstraint(['start_id'], ['stand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('inscrit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inscrit_id'], ['inscription.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['passage_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passage')
    op.drop_table('trace')
    op.drop_table('passage_key')
    op.drop_table('stand')
    op.drop_table('inscription')
    op.drop_table('editions_parcours')
    op.drop_table('parcours')
    op.drop_table('edition')
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
