"""passage arg key peut etre null et plus de creationdate pour un passage

Revision ID: b97b5e6296ac
Revises: d8c3953b1a6e
Create Date: 2024-10-27 19:57:36.160499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b97b5e6296ac'
down_revision = 'd8c3953b1a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passage', schema=None) as batch_op:
        batch_op.alter_column('key_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('key_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
