"""empty message

Revision ID: d8c3953b1a6e
Revises: 11880aec8dbf
Create Date: 2024-10-25 16:40:19.691619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c3953b1a6e'
down_revision = '11880aec8dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('present', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('end', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.drop_column('end')
        batch_op.drop_column('present')

    # ### end Alembic commands ###
